blank_issues_enabled: true
contact_links:
  - name: ESIP GSOC GitHub page
    url: http://github.com/ESIPFed/gsoc
    email: lab@esipfed.org 
    about: Please ask questions about ESIP Summer of Code ideas here.
