blank_issues_enabled: true
contact_links:
  - name: ESIP GSOC GitHub page
    url: http://github.com/ESIPFed/gsoc
    about: Please review this page for information about ESIP Summer of Code (contact details are at end of page) .
